### PR TITLE
Always ref type

### LINKED ISSUE #17: Trailing use isn't padded by comments and whitespace
For example this doesn't work as a use
```rust
use core_plugin::combat::{
    Foo, Bar, Baz,
};
```
but this does
```rust
use core_plugin::combat::{Foo, Bar, Baz,};
```

### PR DESCRIPTION
**Pull request by IsseW**
Fixes some padding issues, so this closes #17 .

Adds Ariadne error printing for the value conversion step.

Adds a marker for the `FromBauble` type that the type should always be parsed as a reference.

### CODE REVIEW

File: bauble/src/value/mod.rs [hunk 1]
```diff
@@ -459,18 +476,56 @@ pub fn convert_values<C: AssetContext>(
...
+                        Label::new(e.span.into_range())
+                            .with_message("Here")
+                            .with_color(Color::Red),
+                    )
+                    .finish()
+                    .eprint(Source::from(source))
+                    .unwrap()
+            }
+        }
+    }
```
Comment (MavethGH) [inline bauble/src/value/mod.rs:526]: Does this need to have its own scope? It doesn't look like it but I don't know `ariadne` well, so I could be missing something.

File: bauble_macro_util/src/lib.rs [hunk 2]
```diff
@@ -676,12 +678,27 @@ pub fn derive_bauble_derive_input(
 
                     Ok(())
                 }
+                "always_ref" => {
+                    if flatten {
+                        Err(meta.error("duplicate `always_ref` attribute"))?
+                    }
```
Comment (MavethGH) [inline bauble_macro_util/src/lib.rs:684]: Does this mean that flatten implies always_ref? If so, the error message should mention that.

**Review by MavethGH — COMMENTED** [review]
Looks good! I have a few questions to make sure I understand the code properly, but other than that and one typo, everything looks perfect.

File: bauble_macro_util/src/lib.rs (hunk 2 above)
Comment (IsseW) [reply bauble_macro_util/src/lib.rs:684]: I've just forgotten to change it to `alway_ref`, but that's a good point, flatten and always_ref are incompatible so should error there too.

File: bauble/src/value/mod.rs (hunk 1 above)
Comment (IsseW) [reply bauble/src/value/mod.rs:526]: It doesn't need to, but did it more to keep the uses in the scope.

**Review by MavethGH — APPROVED** [review]
